default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rails_test_10_dev

test:
  <<: *default
  database: rails_test_10_test

production:
  <<: *default
  database: rails_test_10_production
